config/routes.rb
Rails.application.routes.draw do
  post 'sessions/create'

  get 'login/index'
  get 'login' => 'login#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messaging</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/index.html.haml
#login
  = form_tag sessions_create_path, :method => :post do
    #input
      %input{ placeholder: "User name"}
      %select
        %option{value: "strict"}
          Strict
        %option{value: "yoda"}
          Yoda
        %option{value: "valley_girl"}
          Valley Girl
        %option{value: "binary_code"}
          Binary Code
      %input{ type: :submit, class: :submit }